# Generated by Django 6.0.1 on 2026-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
