# Generated by Django 6.0.1 on 2026-01-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0002_alter_productmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='name',
            new_name='brand',
        ),
    ]
