# Generated by Django 6.0.1 on 2026-01-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0004_productmodel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.CharField(default='Unknow', max_length=1000),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='display',
            field=models.FloatField(default=15.6),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='graphics',
            field=models.CharField(default='Integrated', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='os',
            field=models.CharField(default='Windows', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='review',
            field=models.CharField(default='No reviews yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='processor',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='rom',
            field=models.IntegerField(default=0),
        ),
    ]
