# Generated by Django 6.0.1 on 2026-01-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0005_productmodel_description_productmodel_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='Laptop', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
