# Generated by Django 6.0.1 on 2026-01-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0006_productmodel_category_productmodel_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='quantity',
            new_name='quentity',
        ),
    ]
