# Generated by Django 6.0.1 on 2026-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=200)),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('content', models.TextField(default='No Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
