# Generated by Django 6.0.1 on 2026-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='Not Uploaded', upload_to='media/'),
        ),
    ]
