# Generated by Django 6.0.1 on 2026-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAPP', '0002_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='short_description',
            field=models.CharField(default='No Description', max_length=300),
        ),
    ]
